version: "3.9"
services:
  backend:
    image: ${DOCKERHUB_USERNAME:-kozzyvizzy}/ai-stock-trader-backend:${TAG:-latest}
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-defaultpassword}@db:5432/${POSTGRES_DB:-management}
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    image: ${DOCKERHUB_USERNAME:-kozzyvizzy}/ai-stock-trader-frontend:${TAG:-latest}
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    networks:
      - app-network

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-defaultpassword}
      POSTGRES_DB: ${POSTGRES_DB:-management}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  proxy:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres_data:
