name: Build and push Docker images

on:
  push:
    branches:
      - main
      - test
      - dev
  pull_request:
    branches:
      - main
      - test
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Oletetaan, että jokaisella kokonaisuudella on oma Dockerfile-kansio
      # Toista tämä jokaiselle kokonaisuudelle (esim. management, agent, modules, jne.)

      - name: Build and push management system image
        uses: docker/build-push-action@v5
        with:
          context: ./management-system
          file: ./management-system/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ai-stock-trader-management:${{ github.ref_name }}
