name: Build and push Docker images

on:
  push:
    branches: [main, Dev, Test]
  pull_request:
    branches: [main, Dev, Test]

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Docker tag based on branch
        id: set_tag
        run: |
          case "${GITHUB_REF_NAME}" in
            main)
              TAG="latest"
              ;;
            Test)
              TAG="test"
              ;;
            Dev)
              TAG="dev"
              ;;
            *)
              echo "Unknown branch. Skipping image push."
              exit 1
              ;;
          esac
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./management-system/backend
          file: ./management-system/backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ai-stock-trader-backend:${{ steps.set_tag.outputs.tag }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./management-system/frontend
          file: ./management-system/frontend/Dockerfile
          target: production
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ai-stock-trader-frontend:${{ steps.set_tag.outputs.tag }}
