name: Validate PR source and target branches

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  check-branch-direction:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR source and target branches
        env:
          BASE_REF: ${{ github.event.pull_request.base.ref }}
          HEAD_REF: ${{ github.event.pull_request.head.ref }}
        run: |
          echo "PR base branch: $BASE_REF"
          echo "PR head branch: $HEAD_REF"

          BASE_REF_LC="${BASE_REF,,}"
          HEAD_REF_LC="${HEAD_REF,,}"

          if [[ "$BASE_REF_LC" == "dev" && "$HEAD_REF_LC" =~ ^feature/.* ]]; then
            echo "Valid: feature/* → Dev"
            exit 0
          elif [[ "$BASE_REF_LC" == "test" && "$HEAD_REF_LC" == "dev" ]]; then
            echo "Valid: Dev → Test"
            exit 0
          elif [[ "$BASE_REF_LC" == "main" && "$HEAD_REF_LC" == "test" ]]; then
            echo "Valid: Test → main"
            exit 0
          else
            echo "::error ::PR branch direction is not allowed. Only feature/* → Dev, Dev → Test, or Test → main PRs are permitted."
            exit 1
          fi
