name: Validate PR source and target branches

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  check-branch-direction:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR source and target branches
        env:
          BASE_REF: ${{ github.event.pull_request.base.ref }}
          HEAD_REF: ${{ github.event.pull_request.head.ref }}
        run: |
          echo "PR base branch: $BASE_REF"
          echo "PR head branch: $HEAD_REF"

          if [[ "$BASE_REF" == "dev" && "$HEAD_REF" == feature/* ]]; then
            echo "Valid: feature/* → dev"
            exit 0
          elif [[ "$BASE_REF" == "test" && "$HEAD_REF" == "dev" ]]; then
            echo "Valid: dev → test"
            exit 0
          elif [[ "$BASE_REF" == "main" && "$HEAD_REF" == "test" ]]; then
            echo "Valid: test → main"
            exit 0
          else
            echo "::error ::PR branch direction is not allowed. Only feature/* → dev, dev → test, or test → main PRs are permitted."
            exit 1
          fi
